from PySide6.QtCore import QTimer, Qt, Signal
from PySide6.QtWidgets import QFileDialog, QWidget

from promptlet_client.view.message_widget import MessageWidget
from promptlet_client.view.ui_loader import load_ui
from promptlet_client.view.styles import (
    APP_STYLESHEET,
    RESET_BUTTON_STYLESHEET,
    SETTINGS_BUTTON_STYLESHEET,
    TITLE_STYLESHEET,
)


class ChatView(QWidget):
    settings_requested = Signal()
    reset_requested = Signal()
    question_submitted = Signal(str)
    closing = Signal()
    documents_requested = Signal()
    pdf_selected = Signal(str)
    document_changed = Signal(object)

    def __init__(self, parent=None) -> None:
        super().__init__(parent)

        self.setWindowTitle("Promptlet")
        self.resize(1200, 800)
        self.setStyleSheet(APP_STYLESHEET)

        self._load_ui()
        self._apply_styles()
        self._connect_signals()
        self.set_waiting(False)

    def _load_ui(self) -> None:
        load_ui(self, "chat_view.ui")

    def _apply_styles(self) -> None:
        self.settings_btn.setStyleSheet(SETTINGS_BUTTON_STYLESHEET)
        self.reset_btn.setStyleSheet(RESET_BUTTON_STYLESHEET)
        self.title_label.setStyleSheet(TITLE_STYLESHEET)
        self.status_label.setStyleSheet("color:#aaaaaa; font-size:14px;")
        self.chat_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.chat_area.verticalScrollBar().rangeChanged.connect(self._scroll_after_content_resize)

    def _connect_signals(self) -> None:
        self.settings_btn.clicked.connect(self.settings_requested.emit)
        self.reset_btn.clicked.connect(self.reset_requested.emit)
        self.refresh_documents_btn.clicked.connect(self.documents_requested.emit)
        self.attach_pdf_btn.clicked.connect(self._choose_pdf)
        self.document_input.currentIndexChanged.connect(self._update_document_notice)
        self.document_input.currentIndexChanged.connect(lambda: self.document_changed.emit(self.selected_document()))
        self.question_input.returnPressed.connect(self._emit_question)

    def _emit_question(self) -> None:
        question = self.question_input.text().strip()
        if question and self.question_input.isEnabled():
            self.question_submitted.emit(question)

    def clear_question(self) -> None:
        self.question_input.clear()

    def _choose_pdf(self) -> None:
        filename, _ = QFileDialog.getOpenFileName(self, "Attach PDF", "", "PDF documents (*.pdf)")
        if filename:
            self.pdf_selected.emit(filename)

    def selected_document(self) -> dict | None:
        return self.document_input.currentData()

    def configure_documents(self, enabled: bool, chat_type: str = "normal") -> None:
        self._documents_enabled = enabled
        self._chat_type = chat_type
        self.title_label.setText("PDF chat" if chat_type == "pdf" else "Normal chat")
        self.document_controls.setVisible(chat_type == "pdf")
        self.document_controls.setEnabled(enabled)
        self.set_documents([])

    def set_documents(self, documents: list[dict], selected_id: str | None = None) -> None:
        self.document_input.blockSignals(True)
        self.document_input.clear()
        self.document_input.addItem("Select a prepared PDF", None)
        for document in documents:
            self.document_input.addItem(f"{document['name']} [{document['document_id']}]", document)
            if document["document_id"] == selected_id:
                self.document_input.setCurrentIndex(self.document_input.count() - 1)
        self.document_input.blockSignals(False)
        self._update_document_notice()

    def _update_document_notice(self) -> None:
        document = self.selected_document()
        if getattr(self, "_chat_type", "normal") == "normal":
            text = "Normal chat — conversation history is sent to your configured provider."
        elif document:
            text = (f"Selected: {document['name']}. Answers are generated by AskTheBook's configured LM Studio server, "
                    "not the normal-chat endpoint. Each question is independent; previous messages are not sent.")
        elif getattr(self, "_documents_enabled", False):
            text = "PDF chat — attach a PDF or select a prepared document. Each question is independent; AskTheBook does not receive conversation history."
        else:
            text = "Enable AskTheBook in Settings to attach a PDF."
        self.document_notice.setTextFormat(Qt.PlainText)
        self.document_notice.setText(text)

    def set_waiting(self, waiting: bool) -> None:
        self.question_input.setDisabled(waiting)
        self.reset_btn.setDisabled(waiting)
        self.settings_btn.setDisabled(waiting)
        self.document_controls.setEnabled(not waiting and getattr(self, "_documents_enabled", False))
        self.status_label.setText("Assistant is thinking..." if waiting else "")

    def add_chat_line(
        self,
        speaker: str,
        text: str,
        color: str,
        is_user: bool = False,
        metadata=None,
    ) -> None:
        message = MessageWidget(
            speaker=speaker,
            text=text,
            color=color,
            is_user=is_user,
            metadata=metadata,
        )

        insert_index = max(0, self.messages_layout.count() - 1)
        self._scroll_to_latest_pending = True
        self.messages_layout.insertWidget(insert_index, message)
        QTimer.singleShot(0, self.scroll_to_bottom)

    def _scroll_after_content_resize(self, _minimum: int, _maximum: int) -> None:
        if getattr(self, "_scroll_to_latest_pending", False):
            self.scroll_to_bottom()
            self._scroll_to_latest_pending = False

    def scroll_to_bottom(self) -> None:
        scrollbar = self.chat_area.verticalScrollBar()
        scrollbar.setValue(scrollbar.maximum())

    def clear_chat(self) -> None:
        while self.messages_layout.count() > 1:
            item = self.messages_layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()

    def render_session(self, session) -> None:
        self.clear_chat()
        for message in session.messages:
            if message.role == "user":
                self.add_chat_line("User", message.content, "#00bfff", is_user=True, metadata=message)
            elif message.role == "assistant":
                self.add_chat_line("Assistant", message.content, "#21f39b", is_user=False, metadata=message)

    def closeEvent(self, event) -> None:
        self.closing.emit()
        super().closeEvent(event)
